<?php
/**
 * @file
 * Code for the bcl_layout feature.
 */

include_once 'bcl_layout.features.inc';

/**
 * Implements hook_menu_alter().
 */
function bcl_layout_menu_alter(&$items) {
  // Remove the Hybridauth tab.
  unset($items['user/%user/hybridauth']);
}

/**
 * Implements hook_oauth2_login_enabled().
 */
function bcl_layout_oauth2_login_enabled($enabled) {
  // Enable or disable the link 'user/login'.
  db_update('menu_links')
    ->fields(array(
        'hidden' => ($enabled ? 1 : 0),
      ))
    ->condition('menu_name', 'user-menu')
    ->condition('link_path', 'user/login')
    ->condition('router_path', 'user/login')
    ->condition('plid', 0)
    ->condition('module', 'menu')
    ->execute();

  // Disable or enable the link 'user/oauth2_login'.
  db_update('menu_links')
    ->fields(array(
        'hidden' => ($enabled ? 0 : 1),
      ))
    ->condition('menu_name', 'user-menu')
    ->condition('link_path', 'user/oauth2_login')
    ->condition('router_path', 'user/oauth2_login')
    ->condition('plid', 0)
    ->condition('module', 'system')
    ->execute();

  // Clear the cache and rebuild the menu.
  menu_cache_clear('user-menu');
}
