
Drupal installation profile for B-Translator Client.

* Installation

  Assuming that we have a minimal ubuntu server 14.04 (trusty),
  B-Translator Client can be installed in it like this:
  #+BEGIN_EXAMPLE
  mkdir /var/chroot
  cd /var/chroot/
  git clone https://github.com/B-Translator/btr_client.git
  cp btr_client/install/settings.sh btr_client/bcl.sh
  vim btr_client/bcl.sh
  nohup time nice btr_client/install/chroot.sh btr_client/bcl.sh &
  tail -f nohup.out
  less -r nohup.out
  #+END_EXAMPLE

  This will install in ~/var/chroot/~ a minimal ubuntu system,
  B-Translator Client, and everything that is needed for the normal
  work of the system. It will also make the neccessary common
  configurations of the system.

  The installation script will also create the init script
  ~/etc/init.d/chroot-bcl~, which can be used to start and stop the
  services inside the chroot:
  #+BEGIN_EXAMPLE
  /etc/init.d/chroot-bcl start
  /etc/init.d/chroot-bcl stop
  #+END_EXAMPLE


* Installation in a docker container

  This is almost the same as the installation above, except that
  instead of ~install/chroot.sh~ you call ~install/docker.sh~:
  #+BEGIN_EXAMPLE
  nohup time nice btr_client/install/docker.sh btr_client/bcl.sh &
  #+END_EXAMPLE

  Then to start and stop B-Translator Client you do:
  #+BEGIN_EXAMPLE
  docker.io start bcl
  docker.io stop bcl
  #+END_EXAMPLE

  Compared to the installation with chroot, docker has the advantage
  that it is platform independent (the host system does not have to be
  Ubuntu or Debian).


* Building with docker

  Another way is to use the command =docker build= to build an image
  and then =docker run= to create a container from this image:
  #+BEGIN_EXAMPLE
  vim btr_client/install/settings.sh
  docker.io build --tag=btr_client btr_client/
  docker.io run -d --name=bcl --hostname=example.org \
                -p 80:80 -p 443:443 btr_client
  #+END_EXAMPLE


* What is B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.


* Contacts

  - Email: info@btranslator.org

  - Follow on Twitter: https://twitter.com/b_translator

  - Discussion group/forum
    + Email: /btranslator@googlegroups.com/
    + Web: https://groups.google.com/forum/?fromgroups&hl=en#!forum/btranslator
    + Google+ Community: https://plus.google.com/u/0/communities/109327047119841706609

  - Chat/IRC: *#btranslator* on *irc.freenode.net*

  - Misc
    + Homepage: http://info.btranslator.org
    + Wiki: https://github.com/B-Translator/btr_client/wiki
    + Issues: https://github.com/B-Translator/btr_client/issues


* Sites

  Sites using B-Translator:
  - https://l10n.org.al - Albanian translations.

  To install and setup your site you would need some basic skills on
  Ubuntu server administration and Drupal administration.
